---
sudo: false
addons:
  apt:
    packages:
      - aspell
      - aspell-en
language: perl
perl:
  - blead
  - dev
  - '5.26'
  - '5.24'
  - '5.22'
  - '5.20'
  - '5.18'
  - '5.16'
  - '5.14'
matrix:
  allow_failures:
    - perl: blead
  include:
    - env: COVERAGE=1
      perl: '5.26'
env:
  global:
    - AUTHOR_TESTING=1
    - RELEASE_TESTING=1
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
notifications:
  email:
    on_failure: always
    on_success: change
    recipients:
      - dev-ci@maxmind.com
  slack:
    rooms:
      secure: "P8gvOlzjHNRM3+OECMVhRRQy7hgtF6Nefx/8gpRhsNJ1baiJhbmmoaZ6MbGhjEaE1KeJ6KQADThGmOEnN3vYEGq/maXQio3x6HtJMbuRBmqSaAk6G5fq/u6R6laomGd3l6pjfsT3e1eTT3izRx5rfc7Vk8onrIkuiEIu0Jz8G3MOaJ3jI38OphqKgkoDaNNl5THxvGsKaEWQW5tv2nethDkfTXt+vchL3FNB73GZwXruxMLsULhEuJ2lMDvJDoDK/ZutwJ5YHpKGEhJ5nKOR/jexDkxiHM6/GYwbPv30uWGKl0T3NzH1BObZz36L7eMSlgVVG0gT1VjiJG3ZXPhc8AzCzCcFKarmbNjNuRCSM8i1G+GXaAXINBqdwxgei7y9KWA7X/seHeK78liJdq/qfxniLpF9GFAuTq73zNMCU0b2Zq5oPWq2R9+Un94eRJq/wnIujWeMIJN68ToJR7Cwx4CZpouM3Tz/rH5pv4OxCepD83yDrVDsgT/AGtWLrTkniUfJVlc1ZW8BIzaqcXNrMFD5ZyZeraei5Lp2Z/ZY99KTzTYrF67c81LyGclr/HutcZXTjtA4lANCuVMWjqwskBMUuXP0YK6Le1NP6nIt2RTqlXhhwSp+L3P2137Czfdl6vgj6hi4WfE/f8iieVoJDv1J+Gio6Kw4KRvJoEsP9po=\n"
### __app_cisetup__
# ---
# email_address: dev-ci@maxmind.com
# force_threaded_perls: 0
# github_user: maxmind

### __app_cisetup__
